### ISSUE TITLE
add option to let `teosd` run as a background daemon

### ISSUE THREAD

**Issue by carboncls** [talaia-labs/rust-teos#112]
Would be great to have this option, like python-teos did. It's just so much more convenient!
Ideally, the option could be set in the teos.toml file, so it's not needed to be passed on every start up.

**Comment by sr-gi** [comment]
I had this in mind when working on the rust codebase, but turns out this is not the recommended way to go.

https://stackoverflow.com/questions/61671013/how-to-make-rust-run-gracefully-in-the-background-and-daemonize

I will keep this issue open anyway since it is, actually, something I'd like to add provided we can find an easy and convenient way to do so.

**Comment by carboncls** [comment]
Oh ok, I see. So I can just use `./webserver start & teosd [OPTION]`?

**Comment by sr-gi** [comment]
No, currently there is no option for it to run on daemon mode, but you can just do something like:

```
teosd >> log.txt &
```

And that should do

**Comment by sr-gi** [comment]
@carboncls [This](https://github.com/talaia-labs/rust-teos/pull/138) may be relevant
