### ISSUE TITLE
Plugin error when starting CLN

### ISSUE THREAD

**Issue by grubles** [talaia-labs/rust-teos#152]
Running CLN v22.11rc1 and rust-teos at 832dd71ae5b8b7875f892d12851379349812b0cd

Printed to console when starting `lightningd`:

```
Error: Got unexpected message Err(invalid type: string "cln:getmanifest#13", expected usize) from lightningd
```

CLN logs:

```
2022-11-13T01:15:07.362Z INFO    plugin-watchtower-client: Killing plugin: exited before replying to getmanifest
```

**Comment by sr-gi** [comment]
Yep, I'm aware of this.

Looks like this is due to the last release of CoreLN using the latest version of `cln-plugin` (the Rust interface for plugins) while this was publicly released yesterday, so our plugin os not.

This should be solved once we patch the `watchtower-plugin` to match the introduced changes.

Quoting @cdecker from CoreLN Discord:

> sr_gi: Has something recently changed in how plugins interact with `lightningd`? I've upgraded from `v0.11.0.1` to `v0.12.1` and suddenly I'm getting:

```
Error: Got unexpected message Err(invalid type: string "cln:getmanifest#14", expected usize) from lightningd

2022-11-04T13:51:02.113Z INFO    plugin-watchtower-client: Killing plugin: exited before replying to getmanifest
```

> cdecker: That the rust cln-plugin library. I think it most likely is the switch from numeric-only call IDs to serde_json::Value. So using the version in the repo will fix that. Also I'll publish the latest version to crates.io once I get home.
