### ISSUE TITLE
Unable to connect to watchtowers through TOR

### ISSUE THREAD

**Issue by CMDRZOD** [talaia-labs/rust-teos#92]
Hi there. I have 2 watchtowers running, one local and one remote. 

Unfortunately I must open a port and connect direct to the remote tower. This works as expected. I have TOR setup and get a TOR address when starting the watchtower. However local and remote instances of the watchtower-client are unable to connect.

lightning-cli registertower 021366c98eabdd5ecca68ceb4ebfcda58f24b1e6069e2c168c7c246b67e7827baa@7lqfpop2kbfplmg7vuuei5npfgyxmoh3du6zjlcgtu55ybp73hj2k2id.onion:2121
"Cannot connect to the tower. Connection refused"

TEOSD:
[teosd] Loading configuration from file
778Z INFO  [teosd] tower_id: 021366c98eabdd5ecca68ceb4ebfcda58f24b1e6069e2c168c7c246b67e7827baa
780Z INFO  [teosd] Last known block: 00000000000000000008708de7105faece0fbed942b0f601b971d87c62b4992a
780Z INFO  [teosd] Bootstrapping from backed up data
781Z INFO  [teosd] Bootstrap completed. Turning on interfaces
782Z INFO  [teosd] Starting up hidden tor service
782Z INFO  [teosd] Tower ready
784Z INFO  [teos::api::tor] onion service: 7lqfpop2kbfplmg7vuuei5npfgyxmoh3du6zjlcgtu55ybp73hj2k2id.onion:2121

Any pointers on how I can get TOR working? I already use tor on both local and remote machines for bitcoind and c-lighting which are working as expected. I can connect to bitcoind and lightning clients through tor but the watchtowers do not want to connect.

**Comment by meryacine** [comment]
I think the plugin can only connect to clearnet urls ATM, as we don't do anything special when we notice that the url ends with `.onion` (route it through tor or something).
I think if you prefix your `lightning-cli` command with `torsocks` it might work.

**Comment by meryacine** [comment]
> I think if you prefix your lightning-cli command with torsocks it might work.

Well, this actually won't work, because the register request is actually sent from another application (`lightningd`) and not `lightning-cli`. That's why you will see these broken logs in the daemon after the `connection refused` error from the CLI:

![image](https://user-images.githubusercontent.com/56920956/184550985-adfdda17-5b47-4818-a6da-7282f3563c4c.png)

Starting `lightningd` with torsocks should fix it, but for some reason if fails to start when used with torsocks.
So, right now, the watchtower plugin isn't usable with Tor.

**Comment by sr-gi** [comment]
We should look into this for the upcoming `v0.1.2` release.

**Comment by sr-gi** [comment]
@CMDRZOD FYI this was added in #96. We just tagged the first release candidate for `v0.1.2` which includes this functionality.
